# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Tavringer Romani spellchecker"
rmu = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Tavringer Romani, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
rmu = "TRANSLATE: A spellchecker for Tavringer Romani, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.rmu"

[windows]
system_product_code = "{85CB5F2A-CB34-4309-A43C-FCB5CD166169}_is1"
legacy_product_codes = [
    { value = "8B865450-2219-4083-BA0A-2DE1C47A966D", kind = "nsis" },
    { value = "1CE95BC5-DCFC-4649-803E-C67AD4121937", kind = "nsis" }
]

[package.speller]
name = "Tavringer Romani"
version = "0.1.1"

[package.grammar]
name = "Tavringer Romani"
version = "0.1.0"

[package.tts-textproc]
name = "Tavringer Romani"
version = "0.1.0"

[package.hyphenator]
name = "Tavringer Romani"
version = "0.1.0"
