template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "tavr1235"
__REPO__ = "lang-rmu-x-testing"
__UND2C__ = "rmu"
__UNDEFINED__ = "Tavringer Romani"
__UND__ = "rmu"
