template = "https://github.com/giellalt/template-lang-und"
rev_id = 272
template_sha = "f40ff07ea2383e4e83e8ad0ff88b795ceaf841e6"

[replacements]
__GLOTTOLOG_ID__ = "tavr1235"
__REPO__ = "lang-rmu-x-testing"
__UND2C__ = "rmu"
__UNDEFINED__ = "Tavringer Romani"
__UND__ = "rmu"
